### ISSUE TITLE
Compilation error for esp32c6 on MacOS

### ISSUE THREAD

**Issue by skoky** [ivmarkov/esp-idf-matter#10]
I am trying to run light example with connect esp32c6 dev board like this 

```
MCU=esp32c6 cargo +esp espflash flash --target riscv32imac-esp-espidf --example light --features examples --monitor
```

And I am getting compilation errors related to Mutexes like this:

```

error[E0599]: the method `wait` exists for struct `Signal<EspRawMutex, bool>`, but its trait bounds were not satisfied
   --> src/ble.rs:250:18
    |
248 | /             self.context
249 | |                 .ind_in_flight
250 | |                 .wait(|in_flight| (!*in_flight).then_some(()))
    | |                 -^^^^ method cannot be called on `Signal<EspRawMutex, bool>` due to unsatisfied trait bounds
    | |_________________|
    |
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |       pub struct EspRawMutex(super::CriticalSection);
    |       ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `lock_if` exists for struct `IfMutex<EspRawMutex, IndBuffer>`, but its trait bounds were not satisfied
   --> src/ble.rs:253:44
    |
253 |             let mut ind = self.context.ind.lock_if(|ind| !ind.data.is_empty()).await;
    |                                            ^^^^^^^ method cannot be called on `IfMutex<EspRawMutex, IndBuffer>` due to unsatisfied trait bounds
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `modify` exists for struct `Signal<EspRawMutex, bool>`, but its trait bounds were not satisfied
   --> src/ble.rs:257:40
    |
257 |             self.context.ind_in_flight.modify(|in_flight| {
    |             ---------------------------^^^^^^ method cannot be called on `Signal<EspRawMutex, bool>` due to unsatisfied trait bounds
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `with` exists for struct `IfMutex<EspRawMutex, IndBuffer>`, but its trait bounds were not satisfied
   --> src/ble.rs:280:14
    |
278 | /         self.context
279 | |             .ind
280 | |             .with(|ind| {
    | |             -^^^^ method cannot be called on `IfMutex<EspRawMutex, IndBuffer>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |       pub struct EspRawMutex(super::CriticalSection);
    |       ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

Some errors have detailed explanations: E0277, E0432, E0599, E0782.
For more information about an error, try `rustc --explain E0277`.
skoky@mini esp-idf-matter % MCU=esp32c6 cargo espflash flash --target riscv32imac-esp-espidf --example light --features examples --monitor 
[2025-06-11T16:47:47Z INFO ] Detected 2 serial ports
[2025-06-11T16:47:47Z INFO ] Ports which match a known common dev board are highlighted
[2025-06-11T16:47:47Z INFO ] Please select a port
[2025-06-11T16:47:49Z INFO ] Serial port: '/dev/cu.usbmodem211301'
[2025-06-11T16:47:49Z INFO ] Connecting...
[2025-06-11T16:47:49Z INFO ] Using flash stub
   Compiling proc-macro2 v1.0.95
   Compiling zeroize v1.8.1
   Compiling libc v0.2.172
   Compiling aho-corasick v1.1.3
   Compiling serde v1.0.219
   Compiling once_cell v1.21.3
   Compiling cfg-if v1.0.1
   Compiling typenum v1.18.0
   Compiling generic-array v0.14.7
error: could not compile `cfg-if` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `zeroize` (lib) due to 1 previous error
error[E0463]: can't find crate for `core`
  |
  = note: the `riscv32imac-esp-espidf` target may not be installed
  = help: consider downloading the target with `rustup target add riscv32imac-esp-espidf`

error[E0463]: can't find crate for `core`
  |
  = note: the `riscv32imac-esp-espidf` target may not be installed
  = help: consider downloading the target with `rustup target add riscv32imac-esp-espidf`

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
skoky@mini esp-idf-matter % MCU=esp32c6 cargo +esp espflash flash --target riscv32imac-esp-espidf --example light --features examples --monitor
[2025-06-11T16:48:48Z INFO ] Detected 2 serial ports
[2025-06-11T16:48:48Z INFO ] Ports which match a known common dev board are highlighted
[2025-06-11T16:48:48Z INFO ] Please select a port
[2025-06-11T16:48:49Z INFO ] Serial port: '/dev/cu.usbmodem211301'
[2025-06-11T16:48:49Z INFO ] Connecting...
[2025-06-11T16:48:50Z INFO ] Using flash stub
   Compiling esp-idf-matter v0.1.0 (/Users/skoky/mywork/esp-idf-matter)
error: could not compile `esp-idf-matter` (lib) due to 18 previous errors
error[E0432]: unresolved import `rs_matter_stack::netif`
  --> src/netif.rs:23:22
   |
23 | use rs_matter_stack::netif::{Netif, NetifConf};
   |                      ^^^^^ could not find `netif` in `rs_matter_stack`

error[E0432]: unresolved import `rs_matter_stack::netif`
   --> src/wireless.rs:127:26
    |
127 |     use rs_matter_stack::netif::{Netif, NetifConf};
    |                          ^^^^^ could not find `netif` in `rs_matter_stack`

error[E0432]: unresolved import `rs_matter_stack::wireless::svc`
   --> src/wireless.rs:129:36
    |
129 |     use rs_matter_stack::wireless::svc::SvcWifiController;
    |                                    ^^^ could not find `svc` in `wireless`

error[E0432]: unresolved imports `rs_matter_stack::wireless::WifiData`, `rs_matter_stack::wireless::Wireless`, `rs_matter_stack::wireless::WirelessCoex`, `rs_matter_stack::wireless::WirelessCoexTask`, `rs_matter_stack::wireless::WirelessTask`
   --> src/wireless.rs:131:31
    |
131 |         Gatt, GattTask, Wifi, WifiData, Wireless, WirelessCoex, WirelessCoexTask, WirelessTask,
    |                               ^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `WirelessTask` in `wireless`
    |                               |         |         |             |
    |                               |         |         |             no `WirelessCoexTask` in `wireless`
    |                               |         |         no `WirelessCoex` in `wireless`
    |                               |         no `Wireless` in `wireless`
    |                               no `WifiData` in `wireless`
    |
help: a similar name exists in the module
    |
131 -         Gatt, GattTask, Wifi, WifiData, Wireless, WirelessCoex, WirelessCoexTask, WirelessTask,
131 +         Gatt, GattTask, Wifi, WifiData, Wireless, WirelessBle, WirelessCoexTask, WirelessTask,
    |
help: a similar name exists in the module
    |
131 -         Gatt, GattTask, Wifi, WifiData, Wireless, WirelessCoex, WirelessCoexTask, WirelessTask,
131 +         Gatt, GattTask, Wifi, WifiData, Wireless, WirelessCoex, WirelessCoexTask, WirelessBle,
    |

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:106:10
    |
106 |     ind: IfMutex<EspRawMutex, IndBuffer>,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`

error[E0782]: expected a type, found a trait
   --> src/wireless.rs:141:69
    |
141 |     pub type EspWifiMatterStack<'a, E> = EspWirelessMatterStack<'a, Wifi, E>;
    |                                                                     ^^^^
    |
help: you can add the `dyn` keyword if you want a trait object
    |
141 |     pub type EspWifiMatterStack<'a, E> = EspWirelessMatterStack<'a, dyn Wifi, E>;
    |                                                                     +++

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:126:22
    |
126 |             state <- Mutex::init(RefCell::init(State::init())),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `rs_matter::utils::sync::blocking::Mutex::<R, T>::init`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/blocking.rs:58:13
    |
58  |     impl<R: RawMutex, T> Mutex<R, T> {
    |             ^^^^^^^^ required by this bound in `Mutex::<R, T>::init`
...
69  |         pub fn init<I: Init<T>>(val: I) -> impl Init<Self> {
    |                ---- required by a bound in this associated function

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:127:20
    |
127 |             ind <- IfMutex::init(IndBuffer::init()),
    |                    ^^^^^^^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:127:20
    |
127 |             ind <- IfMutex::init(IndBuffer::init()),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex::<M, T>::init`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:53:8
    |
53  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex::<M, T>::init`
...
65  |     pub fn init<I: Init<T>>(value: I) -> impl Init<Self> {
    |            ---- required by a bound in this associated function

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:125:9
    |
125 | /         init!(Self {
126 | |             state <- Mutex::init(RefCell::init(State::init())),
127 | |             ind <- IfMutex::init(IndBuffer::init()),
128 | |             ind_in_flight: Signal::new(false),
129 | |         })
    | |__________^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`
    = note: this error originates in the macro `$crate::__init_internal` which comes from the expansion of the macro `init` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:125:9
    |
125 | /         init!(Self {
126 | |             state <- Mutex::init(RefCell::init(State::init())),
127 | |             ind <- IfMutex::init(IndBuffer::init()),
128 | |             ind_in_flight: Signal::new(false),
129 | |         })
    | |__________^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`
    = note: this error originates in the macro `$crate::__init_internal` which comes from the expansion of the macro `init` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:128:28
    |
128 |             ind_in_flight: Signal::new(false),
    |                            ^^^^^^^^^^^^^^^^^^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `rs_matter::utils::sync::Signal::<M, S>::new`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/signal.rs:67:8
    |
67  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `Signal::<M, S>::new`
...
70  |     pub const fn new(state: S) -> Self {
    |                  --- required by a bound in this associated function

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:125:9
    |
125 | /         init!(Self {
126 | |             state <- Mutex::init(RefCell::init(State::init())),
127 | |             ind <- IfMutex::init(IndBuffer::init()),
128 | |             ind_in_flight: Signal::new(false),
129 | |         })
    | |__________^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`
    = note: this error originates in the macro `$crate::__init_internal` which comes from the expansion of the macro `init` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex` is not satisfied
   --> src/ble.rs:125:9
    |
125 | /         init!(Self {
126 | |             state <- Mutex::init(RefCell::init(State::init())),
127 | |             ind <- IfMutex::init(IndBuffer::init()),
128 | |             ind_in_flight: Signal::new(false),
129 | |         })
    | |__________^ the trait `embassy_sync::blocking_mutex::raw::RawMutex` is not implemented for `EspRawMutex`
    |
note: there are multiple different versions of crate `embassy_sync` in the dependency graph
   --> /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.7.0/src/blocking_mutex/raw.rs:25:1
    |
25  | pub unsafe trait RawMutex {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ this is the required trait
    |
   ::: src/ble.rs:19:5
    |
19  | use rs_matter::error::ErrorCode;
    |     --------- one version of crate `embassy_sync` used here, as a dependency of crate `rs_matter`
    |
   ::: src/wireless.rs:106:9
    |
106 |     use embassy_sync::mutex::Mutex;
    |         ------------ one version of crate `embassy_sync` used here, as a direct dependency of the current crate
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- this type doesn't implement the required trait
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-sync-0.6.2/src/fmt.rs:219:1
    |
219 | pub trait Try {
    | ------------- this is the found trait
    = help: you can use `cargo tree` to explore your dependency tree
note: required by a bound in `IfMutex`
   --> /Users/skoky/.cargo/git/checkouts/rs-matter-63faec357d04c185/c90ba44/rs-matter/src/utils/sync/mutex.rs:40:8
    |
38  | pub struct IfMutex<M, T>
    |            ------- required by a bound in this struct
39  | where
40  |     M: RawMutex,
    |        ^^^^^^^^ required by this bound in `IfMutex`
    = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `init` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: the method `wait` exists for struct `Signal<EspRawMutex, bool>`, but its trait bounds were not satisfied
   --> src/ble.rs:250:18
    |
248 | /             self.context
249 | |                 .ind_in_flight
250 | |                 .wait(|in_flight| (!*in_flight).then_some(()))
    | |                 -^^^^ method cannot be called on `Signal<EspRawMutex, bool>` due to unsatisfied trait bounds
    | |_________________|
    |
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |       pub struct EspRawMutex(super::CriticalSection);
    |       ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `lock_if` exists for struct `IfMutex<EspRawMutex, IndBuffer>`, but its trait bounds were not satisfied
   --> src/ble.rs:253:44
    |
253 |             let mut ind = self.context.ind.lock_if(|ind| !ind.data.is_empty()).await;
    |                                            ^^^^^^^ method cannot be called on `IfMutex<EspRawMutex, IndBuffer>` due to unsatisfied trait bounds
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `modify` exists for struct `Signal<EspRawMutex, bool>`, but its trait bounds were not satisfied
   --> src/ble.rs:257:40
    |
257 |             self.context.ind_in_flight.modify(|in_flight| {
    |             ---------------------------^^^^^^ method cannot be called on `Signal<EspRawMutex, bool>` due to unsatisfied trait bounds
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |     pub struct EspRawMutex(super::CriticalSection);
    |     ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

error[E0599]: the method `with` exists for struct `IfMutex<EspRawMutex, IndBuffer>`, but its trait bounds were not satisfied
   --> src/ble.rs:280:14
    |
278 | /         self.context
279 | |             .ind
280 | |             .with(|ind| {
    | |             -^^^^ method cannot be called on `IfMutex<EspRawMutex, IndBuffer>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/skoky/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-hal-0.45.2/src/task.rs:850:5
    |
850 |       pub struct EspRawMutex(super::CriticalSection);
    |       ---------------------- doesn't satisfy `_: RawMutex`
    |
    = note: the following trait bounds were not satisfied:
            `EspRawMutex: embassy_sync::blocking_mutex::raw::RawMutex`

```

any advice please?

And BTW, thanks for a great project in Rust!

**Comment by ivmarkov** [comment]
The compilation errors should be fixed now. I didn't test with all Espressif chip variants, but I don't expect any issues.

Ping me if it (still) does not work for you. But should compile in any case.

**Comment by skoky** [comment]
I am flashing the way as it is described in the README.md, using `casrgo espflash...` Let me try another ways

**Comment by skoky** [comment]
I am sorry, I can't figure out how to flash different way. Could add more details into the README.md file please?

**Comment by ivmarkov** [comment]
Just install espflash from git and try again.

**Comment by skoky** [comment]
I installed the espflash with 
```
cargo install espflash --git https://github.com/esp-rs/espflash --force
```
and did clean and 
```
MCU=esp32c6 cargo +esp espflash flash --target riscv32imac-esp-espidf --example light --features examples --monitor
```
and it still failing to the partitions issue

If I run this without the `+esp` as described in README, I am getting compillation error 
```
error[E0463]: can't find crate for `core`
```

**Comment by ivmarkov** [comment]
Pass `--mmu-page-size 32KB` or so when calling `espflash flash`, [as described in the changelog](https://github.com/esp-rs/espflash/blob/main/CHANGELOG.md#added).

As for `+esp` - if you don't pass this, the you need to do `rustup default nightly` as described [here](https://github.com/esp-rs/esp-idf-template?tab=readme-ov-file#alternative-for-risc-v-espressif-socs-only-install--use-upstream-nightly-rust-and-upstream-stable-clang)

**Comment by Vollbrecht** [comment]
you can add the app_descriptor via just putting `esp_idf_svc::sys::esp_app_desc!(true);` at the top of the file. 

@ivmarkov btw because i also see more and more of this error, and adding the app_desc works mitigating this, i created the PR initially in esp-idf-template :D Because while its true that it "theoretically" should be weakly lined in i think esp-idf is cooking something up with there newer stuff... For me adding that fixes that particular error on c6

**Comment by ivmarkov** [comment]
> well, the `cargo espflash` does not have the option `--mmu-page-size` yet. So I am using the `espflash` from master and there is the option present. When I run this, it does not pass and fails to this error:
> 
> ```
> skoky@mini espflash % ./target/release/espflash flash --mmu-page-size 32 ../esp-idf-matter/target/riscv32imac-esp-espidf/debug/examples/light
> [2025-06-13T18:20:58Z WARN ] Monitor options were provided, but `--monitor/-M` flag isn't set. These options will be ignored.
> [2025-06-13T18:20:58Z INFO ] Detected 2 serial ports
> [2025-06-13T18:20:58Z INFO ] Ports which match a known common dev board are highlighted
> [2025-06-13T18:20:58Z INFO ] Please select a port
> [2025-06-13T18:20:59Z INFO ] Serial port: '/dev/cu.usbserial-21130'
> [2025-06-13T18:20:59Z INFO ] Connecting...
> [2025-06-13T18:21:00Z INFO ] Using flash stub
> Error: 
>   × The app descriptor is not present in the project. You need to add the https://github.com/esp-rs/esp-hal/tree/main/esp-bootloader-esp-idf to your project.
> ```
> 
> Maybe I should wait for the `cargo espflash` to be properly released

@skoky 
OK. Here's a set of detailed instructions for you:

1. **STEP 0: `git pull` your `esp-idf-matter` GIT clone**. I just fixed something in there related to the c6 BLE blob version (you haven't hit this issue, as you can't boot the app image yet)

2. Next steps:
```sh
rustup default nightly # ... or add "+esp" to the "cargo espflash ..." command below
cargo install espflash --git https://github.com/esp-rs/espflash # Just in case so that both espflash and cargo-espflash are up to date from GIT
cargo install cargo-espflash --git https://github.com/esp-rs/espflash # This is what you are using actually
MCU=esp32c6 cargo espflash flash --mmu-page-size 32768 --check-app-descriptor false --target riscv32imac-esp-espidf --example light --features examples --monitor
```
